# Generated by Django 4.2.2 on 2023-06-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tutorial')),
                ('name', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=500)),
                ('description', models.TextField()),
            ],
        ),
    ]
