# Generated by Django 4.2.2 on 2023-06-09 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=354)),
                ('address', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='profile')),
                ('cover_image', models.ImageField(upload_to='cover')),
                ('phone', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('nationality', models.CharField(max_length=150)),
                ('language', models.CharField(max_length=550)),
                ('work_experience', models.IntegerField()),
                ('popup_image1', models.ImageField(upload_to='popup')),
                ('popup_image2', models.ImageField(upload_to='popup')),
                ('short_description', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('completed_projects', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialmedia', models.CharField(max_length=150)),
                ('link', models.CharField(max_length=350)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
